### ISSUE TITLE
[Bug / Feature Request] Private Repositories not Supported

### ISSUE THREAD

**Issue by joshwolff1** [aquerium/aquerium#8]
I am not sure if this is a bug or a feature not yet available, but it appears that private repositories are not supported.

Please see [this video](https://youtu.be/nEQsxP1LHrk) for a description of the bug.

If this is indeed a bug, please let me know and I will write out steps to reproduce.

**Comment by tmaster628** [comment]
Hi Josh.

Unfortunately we don't currently support private repos due to API limitations. Sorry for the inconvenience.
